language: node_js
node_js: 10

matrix:
  include:
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/ci.ios.sh
    - ./scripts/upload_artifact.sh
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.58.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/ci.ios.sh
    - ./scripts/upload_artifact.sh
  - language: android
    env:
    - REACT_NATIVE_VERSION=0.59.x
    android:
      components:
      - android-28
      - android-26
      - build-tools-28.0.3
      - tools
      - platform-tools
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      #- sys-img-x86-android-26
      - sys-img-x86_64-android-26
    install:
    # This is cause of react-native: react native's Gradle tasks partially run even without running Detox'
    # compile-from-source flavour :-/
    # TODO find a way to get rid of this step
    - echo yes | sdkmanager ndk-bundle
    - export ANDROID_NDK="$ANDROID_HOME/ndk-bundle"
    # Need to update the tools so we'd have a decent 'emulator' bin and the newer 'avdmanager' (instead of the 'android' bin)
    - echo yes | sdkmanager --update
    - sdkmanager --list
    - ./scripts/install.android.sh
    # Set up emulator
    - avdmanager create avd --force --name Nexus_5X_API_26 --abi x86_64 --device "Nexus 5X" -k "system-images;android-26;default;x86_64"
    - echo "skin.name=1080x1920" >> ~/.android/avd/Nexus_5X_API_26.avd/config.ini
    - echo "vm.heapSize=512" >> ~/.android/avd/Nexus_5X_API_26.avd/config.ini
    - echo "hw.ramSize=1024" >> ~/.android/avd/Nexus_5X_API_26.avd/config.ini
    - /usr/local/android-sdk/tools/emulator @Nexus_5X_API_26 -verbose -no-window -no-snapshot -no-boot-anim -no-accel -noaudio -gpu swiftshader_indirect &
    script:
    - ./scripts/ci.android.sh
#    cache:
#    - directories:
  # Example Projects
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/demo-projects.ios.sh

branches:
  only:
  - travis_integration
  - master

before_install:
- nvm install 10
- pip install awscli --upgrade --user

notifications:
  email: true
  slack:
    secure: ExAwGcI4WlRoi/F2AKMds2eNQZ90susGT2k/CSU1ZQdTL5jaeMW6/i86Uz6Goilnd7qL/1GhlHF9Q48yYtctLVg4zSKH3uclHDDtPfWsF/R7+UWBPYtvhuW2VvL4ota8b0QzUlTz3iS0G3iD4AFqnAZUgYqjSeF1arv+YKOTEXzGyPtj3xjD9TSSjamnSEgGd18RRKpG8FWQr631yOSucikUsYcetV8bUTs6PtjcIC0XK1d1Nv/eMJxSwTQCAptQbxPTO0FBEEH+lQ6H5oQ7mvyNQ7BBUEunUWkUsCh85SsqHLbnCaiPojmI8ICUJBDNSDvzvyt1JJOxnjWtXlLu5xLOQRYeMvr9p66uBMTxTw2LXagSw4bxAf8LHXK/EOssTv+bE6gujNga0FF3jOLTDUZF93OT7TCsrVQrIkiKBl/YoJVc137dz/fUz3wA/JkmqQIV0i9BMUVNYlBGg3J9Omo8nQXTEvqNpYdSfWEm6cZT73kRrdiuittcBXUeWaTkqThmL8KMO5u+InUQhOhhxMmZ/u3DZRTxtHu9ndOdMrWaOmDj4MXpTsml6qelFHMdQoNQubUgdpSb0H0KvGObnQwFR3V2alPT6Ovx1e+XzjBiV2CNP3jHci52JGAlPtGRxctiXUYL9TZYgpJdO/IxJR/lAhA7ZJLsfHGL4LUF65o=
